<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: post.proto

namespace Bar;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class AddPostReq extends \Google\Protobuf\Internal\Message
{
    private $tid = 0;
    private $uid = 0;
    private $title = '';
    private $content = '';

    public function getTid()
    {
        return $this->tid;
    }

    public function setTid($var)
    {
        GPBUtil::checkInt32($var);
        $this->tid = $var;
    }

    public function getUid()
    {
        return $this->uid;
    }

    public function setUid($var)
    {
        GPBUtil::checkInt32($var);
        $this->uid = $var;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;
    }

    public function getContent()
    {
        return $this->content;
    }

    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;
    }

}

class AddPostRsp extends \Google\Protobuf\Internal\Message
{
    private $status = 0;
    private $qid = '';

    public function getStatus()
    {
        return $this->status;
    }

    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;
    }

    public function getQid()
    {
        return $this->qid;
    }

    public function setQid($var)
    {
        GPBUtil::checkString($var, True);
        $this->qid = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0a8c010a0a706f73742e70726f746f120362617222460a0a416464506f73" .
    "74526571120b0a03746964180120012805120b0a03756964180220012805" .
    "120d0a057469746c65180320012809120f0a07636f6e74656e7418042001" .
    "280922290a0a416464506f7374527370120e0a0673746174757318012001" .
    "2805120b0a03716964180220012809620670726f746f33"
));

