<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto

namespace Bar;

require_once('post.pb.php');
use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0a610a0c7365727665722e70726f746f12036261721a0a706f73742e7072" .
    "6f746f32380a07426172436f7265122d0a07416464506f7374120f2e6261" .
    "722e416464506f73745265711a0f2e6261722e416464506f737452737022" .
    "00620670726f746f33"
));

